export const FETCH_DONUTS_REQUEST = "FETCH_DONUTS_REQUEST";
export const FETCH_DONUTS_SUCCESS = "FETCH_DONUTS_SUCCESS";
export const FETCH_DONUTS_FAILURE = "FETCH_DONUTS_FAILURE";
export const BUY_DONUT = "BUY_DONUT";
